### ISSUE TITLE
Error simulating test.dts

### ISSUE THREAD

**Issue by alejandrolabajos** [ucb-bar/spike-devices#9]
I have installed both Linux and Newlib riscv-gnu-toolchain.

First I clonned this repo inside $RISCV path (already exported).

Then running make I get:

![image](https://github.com/user-attachments/assets/a6b45677-f94d-4868-9c67-96b46a94b849)

Just changing its includes from <file.h> to "./file.h" this is solved.

Now running make and also make install without errors.

Then calling spike:

spike --extlib libspikedevices.so --device sifive_uart ./test.dts

I get this: 

![image](https://github.com/user-attachments/assets/59b56773-24bc-4dbe-b3ca-9c7ec209c8d2)

Any help would be appreciated, 
Thanks

**Comment by pranjalchanda08** [comment]
https://github.com/ucb-bar/spike-devices/issues/1#issuecomment-2427406910
@alejandrolabajos Please check the comment above if it helps

**Comment by alejandrolabajos** [comment]
@pranjalchanda08 it works! Thank you a lot. I still don't understand why this lack of documentation even for sample programs.
